package com.undp.fleettracker.models.booking

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class GetBookingsDetails(
    val ApprovalStatus: Int,
    val ApprovalTimeLocaleString: String?,
    val ApprovalTimeStamp: String?,
    val ApprovalTimeStampEpoch: Int,
    val ApproverComments: String?,
    val AuthFileDownloadUrl: String?,
    val AuthorizationLetterFile: String?,
    val BookingCount: Int,
    val BookingId: Int,
    val BookingType: Int,
    val BookingVehicleInfo: BookingVehicleInfo,
    val EndDateLocaleString: String?,
    val EndDateTimeEpoch: Int,
    val EndLocation: String?,
    val EndTime: String?,
    val FilteredCount: Int,
    val FleetId: Int,
    val FleetName: String?,
    val FleetTimeZoneId: String?,
    val FleetTimeZoneInfo: String?,
    val Luggage: Int,
    val NoOfPassengers: Int,
    val RecordId: String?,
    val ReturnTimeEpoch: Int,
    val ReturnTimeLocaleString: String?,
    val ReturnTimeStamp: String?,
    val RouteId: Int,
    val StartDateLocaleString: String?,
    val StartDateTimeEpoch: Int,
    val StartLocation: String?,
    val StartTime: String?,
    val TripCategory: Int,
    val TripLocations: String?,
    val TripLocationsArr: List<TripLocationsArr>,
    val TripStatus: Int,
    val TripType: Int,
    val UserComments: String?,
    val UserEmail: String?,
    val UserId: Int,
    val UserMobileNumber: String?,
    val UserName: String?,
    val VehicleId: Int
):Parcelable